name: Java CI

on:
  push:
    branches:
      - main  # Trigger the action on pushes to the 'main' branch

jobs:
  build:
    runs-on: windows-latest  # Use the latest Windows runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Check out the repository code

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'  # Set the Java version to 11

      - name: Build with Maven
        run: mvn clean package  # Clean and package the Maven project

      - name: Verify JAR
        run: dir target\*.jar  # Verify that the JAR file is generated
